[project]
name = "tpms-tools"
version = "0.1.0"
description = "Tools for encoding TPMS signals as a way to analyze these protocols further"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "scipy>=1.15.1",
]
